[template]
  incoming-hooks = ["Sanity"]

[template.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID = "${process.env.NEXT_PUBLIC_SANITY_PROJECT_ID}"
  NEXT_PUBLIC_SANITY_DATASET = "${process.env.NEXT_PUBLIC_SANITY_DATASET}"
  SANITY_API_WRITE_TOKEN = "${process.env.NEXT_PUBLIC_SANITY_READ_TOKEN}"
  SANITY_API_READ_TOKEN = "${process.env.NEXT_PUBLIC_SANITY_WRUTE_TOKEN}"